### ISSUE TITLE
x86-64.org links are dead

### ISSUE THREAD

**Issue by flungo** [michalmalik/linux-re-101#1]
The links to [www.x86-64.org](http://www.x86-64.org/) appear to be dead. Looking on the [Wayback Machine](https://web-beta.archive.org/details/http://www.x86-64.org), they have not captured any content from that site since mid-2016 so I think it can be assumed that it's not a temporary issue. Both resources referenced from this site, are available on the Wayback Machine at the following URLs:

- https://web-beta.archive.org/web/20160801075139/http://www.x86-64.org/documentation/abi.pdf
- https://web-beta.archive.org/web/20160719053302/http://www.x86-64.org:80/documentation/assembly.html

I would suggest updating the links to point instead to these archived resources.

**Comment by michalmalik** [comment]
Thanks!

 I removed the "Gentle introduction ... " article altogether because of some criticism I found while searching for an alternative link. And looking at it, it's not *that* important.
