### ISSUE TITLE
A must-read section for linux-re-101

### ISSUE THREAD

**Issue by drozdziak1** [michalmalik/linux-re-101#2]
Hey, I'm just starting out in reversing and was wondering if you could pick some links which you find the most important and put them in a must-read section? Like you did on top of the OSX list? Your lists are really amazing, thanks for sharing.

**Comment by michalmalik** [comment]
Hey! Sure, I'll give it a try :)

**Comment by michalmalik** [comment]
Must read section added!

**Comment by drozdziak1** [comment]
Awesome!
